# Generated by Django 3.2.12 on 2023-09-26 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencias',
            fields=[
                ('id_dep', models.AutoField(primary_key=True, serialize=False)),
                ('nom_dep', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dependencias',
            },
        ),
        migrations.CreateModel(
            name='Soat',
            fields=[
                ('id_soa', models.AutoField(primary_key=True, serialize=False)),
                ('nom_emp_soa', models.CharField(max_length=50, null=True)),
                ('fec_exp_soa', models.DateField(null=True)),
                ('fec_vig_soa', models.DateField(null=True)),
                ('fec_ven_soa', models.DateField(null=True)),
            ],
            options={
                'db_table': 'soat',
            },
        ),
        migrations.CreateModel(
            name='Tecnicomecanica',
            fields=[
                ('id_tec', models.AutoField(primary_key=True, serialize=False)),
                ('nom_emp_tec', models.CharField(max_length=50, null=True)),
                ('fec_exp_tec', models.DateField(null=True)),
                ('fec_ven_tec', models.DateField(null=True)),
            ],
            options={
                'db_table': 'tecnicomecanica',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_per', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pas_per', models.CharField(max_length=30)),
                ('nom_per', models.CharField(max_length=30)),
                ('ape_per', models.CharField(max_length=30)),
                ('tel_per', models.CharField(max_length=30)),
                ('dir_per', models.CharField(max_length=30)),
                ('cat_per', models.CharField(max_length=30)),
                ('vig_per', models.DateField(null=True)),
                ('pase_ade_per', models.ImageField(null=True, upload_to='imagenes')),
                ('pase_atr_per', models.ImageField(null=True, upload_to='imagenes')),
                ('dep_per', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.dependencias')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('pla_veh', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('num_lic_veh', models.BigIntegerField()),
                ('cla_veh', models.CharField(max_length=50)),
                ('mar_veh', models.CharField(max_length=50)),
                ('mod_veh', models.IntegerField()),
                ('col_veh', models.CharField(max_length=30)),
                ('num_mot_veh', models.CharField(max_length=50)),
                ('num_cha_veh', models.CharField(max_length=50)),
                ('cil_veh', models.IntegerField()),
                ('tip_car_veh', models.CharField(max_length=50)),
                ('est_veh', models.BooleanField()),
                ('obs_veh', models.CharField(max_length=200, null=True)),
                ('dep_veh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.dependencias')),
            ],
            options={
                'db_table': 'vehiculos',
            },
        ),
        migrations.CreateModel(
            name='VehiculosAsignados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_ing', models.DateTimeField(auto_now_add=True, null=True)),
                ('fec_sal', models.DateTimeField(null=True)),
                ('obs_veh_asi', models.CharField(max_length=200)),
                ('id_per', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='panel.usuarios')),
                ('id_veh', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='panel.vehiculos')),
            ],
            options={
                'db_table': 'vehiculos_asignados',
            },
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='per_asi_veh',
            field=models.ManyToManyField(blank=True, through='panel.VehiculosAsignados', to='panel.Usuarios'),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='soa_veh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.soat'),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='tec_veh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.tecnicomecanica'),
        ),
        migrations.CreateModel(
            name='Preoperacionalesm',
            fields=[
                ('id_pre', models.AutoField(primary_key=True, serialize=False)),
                ('niv_pre', models.CharField(max_length=20)),
                ('man_pre', models.CharField(max_length=20)),
                ('dir_pre', models.CharField(max_length=20)),
                ('gua_pre', models.CharField(max_length=20)),
                ('cha_pre', models.CharField(max_length=20)),
                ('sus_pre', models.CharField(max_length=20)),
                ('fre_pre', models.CharField(max_length=20)),
                ('lla_pre', models.CharField(max_length=20)),
                ('rin_pre', models.CharField(max_length=20)),
                ('tre_pre', models.CharField(max_length=20)),
                ('exo_pre', models.CharField(max_length=20)),
                ('ret_pre', models.CharField(max_length=20)),
                ('man_mec_pre', models.CharField(max_length=20)),
                ('luc_pre', models.CharField(max_length=20)),
                ('dir_stop_pre', models.CharField(max_length=20)),
                ('pit_pre', models.CharField(max_length=20)),
                ('obs_pre', models.CharField(max_length=500)),
                ('fec_pre', models.DateField(null=True)),
                ('pla_pre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.vehiculos')),
            ],
            options={
                'db_table': 'preoperacionalesm',
            },
        ),
        migrations.CreateModel(
            name='Preoperacionalesc',
            fields=[
                ('id_pre', models.AutoField(primary_key=True, serialize=False)),
                ('dir_del_pre', models.CharField(max_length=20)),
                ('dir_tra_pre', models.CharField(max_length=20)),
                ('sis_luc_pre', models.CharField(max_length=20)),
                ('luc_fre_pre', models.CharField(max_length=20)),
                ('luc_rev_pre', models.CharField(max_length=20)),
                ('luc_par_pre', models.CharField(max_length=20)),
                ('vpan_pre', models.CharField(max_length=20)),
                ('vlat_pre', models.CharField(max_length=20)),
                ('vtra_pre', models.CharField(max_length=20)),
                ('limp_pre', models.CharField(max_length=20)),
                ('elat_pre', models.CharField(max_length=20)),
                ('eret_pre', models.CharField(max_length=20)),
                ('pit_pre', models.CharField(max_length=20)),
                ('taco_pre', models.CharField(max_length=20)),
                ('odo_pre', models.CharField(max_length=20)),
                ('gas_pre', models.CharField(max_length=20)),
                ('tem_pre', models.CharField(max_length=20)),
                ('cin_pre', models.CharField(max_length=20)),
                ('alar_pre', models.CharField(max_length=20)),
                ('cha_pue_pre', models.CharField(max_length=20)),
                ('pue_cie_pre', models.CharField(max_length=20)),
                ('esc_acc_pre', models.CharField(max_length=20)),
                ('pas_tec_pre', models.CharField(max_length=20)),
                ('ven_eme_pre', models.CharField(max_length=20)),
                ('alc_vol_pre', models.CharField(max_length=20)),
                ('fre_pri_pre', models.CharField(max_length=20)),
                ('fre_man_pre', models.CharField(max_length=20)),
                ('agu_lim_pre', models.CharField(max_length=20)),
                ('agu_ref_pre', models.CharField(max_length=20)),
                ('ace_mot_pre', models.CharField(max_length=20)),
                ('liq_fre_pre', models.CharField(max_length=20)),
                ('liq_bat_pre', models.CharField(max_length=20)),
                ('ace_hid_pre', models.CharField(max_length=20)),
                ('cor_pre', models.CharField(max_length=20)),
                ('man_pre', models.CharField(max_length=20)),
                ('est_lla_pre', models.CharField(max_length=20)),
                ('pre_lla_pre', models.CharField(max_length=20)),
                ('lab_lla_pre', models.CharField(max_length=20)),
                ('rep_lla_pre', models.CharField(max_length=20)),
                ('señ_eme_pre', models.CharField(max_length=20)),
                ('tac_pre', models.CharField(max_length=20)),
                ('cha_pre', models.CharField(max_length=20)),
                ('gat_pre', models.CharField(max_length=20)),
                ('gua_pre', models.CharField(max_length=20)),
                ('cru_pre', models.CharField(max_length=20)),
                ('her_pre', models.CharField(max_length=20)),
                ('bot_pre', models.CharField(max_length=20)),
                ('ext_pre', models.CharField(max_length=20)),
                ('obs_pre', models.CharField(max_length=500)),
                ('fec_pre', models.DateField(null=True)),
                ('pla_pre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.vehiculos')),
            ],
            options={
                'db_table': 'preoperacionalesc',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_man', models.AutoField(primary_key=True, serialize=False)),
                ('fec_man', models.DateField(null=True)),
                ('tipo_man', models.CharField(max_length=20)),
                ('des_obs_man', models.CharField(max_length=500)),
                ('per_man', models.CharField(max_length=50)),
                ('rec_man', models.CharField(max_length=200)),
                ('id_veh', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='panel.vehiculos')),
            ],
            options={
                'db_table': 'mantenimiento',
            },
        ),
    ]
