# Generated by Django 3.2.12 on 2023-11-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='pase_ade_per',
            field=models.FileField(blank=True, null=True, upload_to='imagenes'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='pase_atr_per',
            field=models.FileField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
