# Generated by Django 3.2.12 on 2024-02-08 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20240207_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodicasm',
            old_name='pla_pre',
            new_name='pla_per',
        ),
    ]
