# Generated by Django 3.2.12 on 2024-02-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_rename_pla_pre_periodicasm_pla_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicasm',
            name='observaciones',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
