# Generated by Django 3.2.12 on 2024-02-08 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_periodicasm_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='soa_veh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.soat'),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='tec_veh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.tecnicomecanica'),
        ),
    ]
