# Generated by Django 3.2.12 on 2024-02-08 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_auto_20240208_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='soa_veh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.soat'),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='tec_veh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.tecnicomecanica'),
        ),
    ]
